# Generated by Django 4.2.5 on 2023-09-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_published'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
